apiVersion: v1
kind: Service
metadata:
  name: kubernates-service
spec:
  type: LoadBalancer
  selector:
    app: spring
  ports:
    - protocol: TCP
      port: 8082 #on this port sevice will be listening
      targetPort: 8081 #on this port my spring app is listening